### PR TITLE
Fix Makefile to allow for compilation on recent versions of Mac OS X

### PR DESCRIPTION
**Pull request by seidnerj**

### CODE REVIEW

**Comment by kennylevinsen** [comment]
`IPPROTO_IP` is what BSD uses, and `SOL_IP` and `IPPROTO_IP` are both 0 on Linux, so you can just change the `setsockopt` call instead of detecting the OS.

**Comment by seidnerj** [comment]
Yes, I know, I just thought leaving the code unchanged and merely updating the Makefile is more elegant.

**Comment by kennylevinsen** [comment]
In my eyes, one line that works on all target platforms is definitely more elegant than 14 lines of platform detection that introduces Linux-specific defines on BSD-like platforms. :)

**Comment by seidnerj** [comment]
Hehe, I guess you’re right but I couldn’t make this call on my own as I
couldn’t confirm it works on all target platforms - if that is indeed the
case, then by all means, let’s change it and be done with it :)

**Pull request closed without merging**
